project:
  type: website
  output-dir: ../docs
website:
  title: "`ssstats`"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: tutorials/index.qmd
        text: Tutorials
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true